#!/usr/bin/env bash
# install/claude-config.sh — deploy ~/.claude/settings.json.
#
# With the private layer (~/dotfiles-private, repo dotfiles-private):
#   deep-merges public + private configs into a GENERATED real file.
# Without it:
#   falls back to symlinking the public config and prints a hint.
#
# Two things differ from opencode-config.sh, both forced by Claude Code:
#   - settings.json is strict JSON, so a leading // comment would break it — and
#     a malformed settings file silently disables EVERY setting in it. The
#     generated marker is therefore a top-level "//" KEY.
#   - the interesting keys are ARRAYS (permissions.allow/deny/ask). jq's `*`
#     replaces arrays rather than unioning them, so a private layer contributing
#     one rule would wipe the whole public list; the filter concatenates them.
#
# Safe to re-run any time:
#   ./install/claude-config.sh [--proxy=<url>] [--dry-run] [--yes]

set -euo pipefail
# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

PUBLIC_CFG="$DOTFILES_ROOT/config/claude/settings.json"
PRIVATE_CFG="$PRIVATE_DIR/claude/settings.json"
TARGET="$HOME/.claude/settings.json"
GENERATED_MARKER="generated by dotfiles"

# Deep-merge public + private, but UNION the permission arrays: jq's `*` would
# let the private layer's short list replace the public one wholesale.
#
# The proxy URL is per-MACHINE, so it belongs in neither repo — it is injected
# here from --proxy=<url>, the same flag the rest of the installer already takes.
# The generated file lives outside any repo, which makes it the right home for a
# machine-specific value. Without --proxy, no env block is written.
merge_configs() {
    jq -s --arg marker "$GENERATED_MARKER — do not edit; edit the source repos instead." \
          --arg proxy "$PROXY" '
        (.[0] // {}) as $pub | (.[1] // {}) as $priv |
        ($pub * $priv)
        | .permissions.allow =
            (($pub.permissions.allow // []) + ($priv.permissions.allow // []) | unique)
        | .permissions.deny =
            (($pub.permissions.deny // []) + ($priv.permissions.deny // []) | unique)
        | .permissions.ask =
            (($pub.permissions.ask // []) + ($priv.permissions.ask // []) | unique)
        | .permissions.additionalDirectories =
            (($pub.permissions.additionalDirectories // [])
             + ($priv.permissions.additionalDirectories // []) | unique)
        | .permissions |= with_entries(select(.value != []))
        | if $proxy == "" then .
          else .env = ((.env // {}) + {
              HTTP_PROXY: $proxy, HTTPS_PROXY: $proxy,
              http_proxy: $proxy, https_proxy: $proxy
          }) end
        | {"//": $marker} + .
    ' "$PUBLIC_CFG" "$PRIVATE_CFG"
}

deploy_generated() {
    mkdir -p "$(dirname "$TARGET")"

    # Replace anything that isn't our own generated output
    if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
        if [ -f "$TARGET" ] && grep -qF "$GENERATED_MARKER" "$TARGET" 2>/dev/null; then
            :  # ours, safe to overwrite in place below
        else
            backup_existing "$TARGET"
        fi
    fi

    if $DRY_RUN; then
        echo "[dry-run] jq -s '<union-merge>' '$PUBLIC_CFG' '$PRIVATE_CFG' > '$TARGET'"
        return
    fi

    merge_configs > "$TARGET.tmp"
    jq empty "$TARGET.tmp" || { rm -f "$TARGET.tmp"; die "generated config is not valid JSON"; }
    grep -qF "$GENERATED_MARKER" "$TARGET.tmp" \
        || { rm -f "$TARGET.tmp"; die "generated config lost its marker key"; }
    mv "$TARGET.tmp" "$TARGET"
    chmod 600 "$TARGET"
    log "generated $TARGET (public + private merged)"
}

deploy_symlink() {
    # REPO_SRC is consumed by handle_conflict() in lib.sh
    # shellcheck disable=SC2034
    REPO_SRC="$(dirname "$PUBLIC_CFG")"
    local name
    name="$(basename "$PUBLIC_CFG")"
    if [ -L "$TARGET" ] && [ "$(readlink "$TARGET")" = "$PUBLIC_CFG" ]; then
        log "already linked: $TARGET"
        return
    fi
    mkdir -p "$(dirname "$TARGET")"
    if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
        handle_conflict "$name" "$TARGET" || return
    else
        run ln -sn "$PUBLIC_CFG" "$TARGET"
    fi
    log "linked public config to $TARGET"
    warn "no private layer detected — proxy env and marketplace paths absent."
    warn "To enable them: create/clone KonstantinPakulev/dotfiles-private and re-run this script."
}

claude_config_main() {
    [ -f "$PUBLIC_CFG" ] || die "missing $PUBLIC_CFG"
    if sync_private_repo && [ -f "$PRIVATE_CFG" ]; then
        command -v jq >/dev/null 2>&1 || die "jq required for merging but not installed (run install/tools.sh)"
        deploy_generated
    else
        deploy_symlink
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    parse_common_args "$@"
    claude_config_main
fi
