#!/usr/bin/env bash
# install/opencode-config.sh — deploy ~/.config/opencode/opencode.jsonc.
#
# With the private layer (~/.dotfiles-private, repo dotfiles-private):
#   deep-merges public + private configs into a GENERATED real file.
# Without it:
#   falls back to symlinking the public config and prints a hint.
#
# The private layer itself is synced by the orchestrator (Stage 4) on full
# installs; run standalone it syncs here first. Safe to re-run any time:
#   ./install/opencode-config.sh [--proxy=<url>] [--dry-run] [--yes]

set -euo pipefail
# shellcheck source-path=SCRIPTDIR
# shellcheck source=lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

PUBLIC_CFG="$DOTFILES_ROOT/config/opencode/opencode.jsonc"
PRIVATE_CFG="$PRIVATE_DIR/opencode/provider.jsonc"
TARGET="$HOME/.config/opencode/opencode.jsonc"
GENERATED_MARKER="generated by dotfiles"

deploy_generated() {
    mkdir -p "$(dirname "$TARGET")"

    # Replace anything that isn't our own generated output
    if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
        if [ -f "$TARGET" ] && grep -qF "$GENERATED_MARKER" "$TARGET" 2>/dev/null; then
            :  # ours, safe to overwrite in place below
        else
            backup_existing "$TARGET"
        fi
    fi

    if $DRY_RUN; then
        echo "[dry-run] jq -s '.[0] * .[1]' '$PUBLIC_CFG' '$PRIVATE_CFG' > '$TARGET'"
        return
    fi

    # Merge first, validate pure JSON, only then add the JSONC comment header
    jq -s '.[0] * .[1]' "$PUBLIC_CFG" "$PRIVATE_CFG" > "$TARGET.tmp"
    jq empty "$TARGET.tmp" || { rm -f "$TARGET.tmp"; die "generated config is not valid JSON"; }
    { printf '// %s — do not edit; edit the source repos instead.\n' "$GENERATED_MARKER"; cat "$TARGET.tmp"; } > "${TARGET}.tmp2"
    mv "${TARGET}.tmp2" "$TARGET"
    rm -f "$TARGET.tmp"
    chmod 600 "$TARGET"
    log "generated $TARGET (public + private merged)"
}

deploy_symlink() {
    # REPO_SRC is consumed by handle_conflict() in lib.sh
    # shellcheck disable=SC2034
    REPO_SRC="$(dirname "$PUBLIC_CFG")"
    local name
    name="$(basename "$PUBLIC_CFG")"
    if [ -L "$TARGET" ] && [ "$(readlink "$TARGET")" = "$PUBLIC_CFG" ]; then
        log "already linked: $TARGET"
        return
    fi
    if [ -e "$TARGET" ] || [ -L "$TARGET" ]; then
        handle_conflict "$name" "$TARGET" || return
    else
        run ln -sn "$PUBLIC_CFG" "$TARGET"
    fi
    log "linked public config to $TARGET"
    warn "no private layer detected — provider configs absent."
    warn "To enable them: create/clone KonstantinPakulev/dotfiles-private and re-run this script."
}

opencode_config_main() {
    [ -f "$PUBLIC_CFG" ] || die "missing $PUBLIC_CFG"
    if sync_private_repo; then
        command -v jq >/dev/null 2>&1 || die "jq required for merging but not installed (run install/tools.sh)"
        deploy_generated
    else
        deploy_symlink
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    parse_common_args "$@"
    opencode_config_main
fi
